In [1]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Youtube01-Psy.csv to Youtube01-Psy.csv
Saving Youtube02-KatyPerry.csv to Youtube02-KatyPerry.csv
Saving Youtube03-LMFAO.csv to Youtube03-LMFAO.csv
Saving Youtube04-Eminem.csv to Youtube04-Eminem.csv
Saving Youtube05-Shakira.csv to Youtube05-Shakira.csv
Saving YoutubeSpamMergedData.csv to YoutubeSpamMergedData.csv
Saving YoutubeSpamMergedData01.csv to YoutubeSpamMergedData01.csv
User uploaded file "Youtube01-Psy.csv" with length 57438 bytes
User uploaded file "Youtube02-KatyPerry.csv" with length 64279 bytes
User uploaded file "Youtube03-LMFAO.csv" with length 64419 bytes
User uploaded file "Youtube04-Eminem.csv" with length 82896 bytes
User uploaded file "Youtube05-Shakira.csv" with length 72706 bytes
User uploaded file "YoutubeSpamMergedData.csv" with length 364447 bytes
User uploaded file "YoutubeSpamMergedData01.csv" with length 364447 bytes


In [2]:
#-------------- Youtube Spam Comment Detector--------------------#

# converting words into vectors to use as fetures to help in classification

#EDA packages
import pandas as pd
import numpy as np


In [3]:
# Ml packages for vectorization of text for feature extraction

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


In [4]:
# Visualization packages

import matplotlib.pyplot as plt
import seaborn as sns


In [5]:
#Dataset from Kaggle

df1 = pd.read_csv("Youtube01-Psy.csv")
df1.head()

COMMENT_ID  ... CLASS
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU  ...     1
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A  ...     1
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  ...     1
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04  ...     1
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw  ...     1

[5 rows x 5 columns]

In [10]:
#load all dataset to mearge them
df2 = pd.read_csv("Youtube02-KatyPerry.csv")
df3 = pd.read_csv("Youtube03-LMFAO.csv")
df4= pd.read_csv("Youtube04-Eminem.csv")
df5= pd.read_csv("Youtube05-Shakira.csv")

In [11]:
frames = [df1,df2,df3,df4,df5]

In [12]:
df_mearged = pd.concat(frames)

In [13]:
df_mearged

COMMENT_ID  ... CLASS
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU  ...     1
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A  ...     1
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  ...     1
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04  ...     1
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw  ...     1
..                                           ...  ...   ...
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA  ...     0
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  ...     0
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs  ...     0
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0  ...     0
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA  ...     0

[1956 rows x 5 columns]

In [20]:
# total size
df_mearged.shape

(1956, 5)

In [22]:
# mearging with keys

keys = ["Psy","KatyPerry","LMFAO","Eminem","Shakira"]

df_with_keys = pd.concat(frames,keys = keys)

df_with_keys

COMMENT_ID  ... CLASS
Psy     0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU  ...     1
        1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A  ...     1
        2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  ...     1
        3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04  ...     1
        4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw  ...     1
...                                                  ...  ...   ...
Shakira 365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA  ...     0
        366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  ...     0
        367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs  ...     0
        368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0  ...     0
        369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA  ...     0

[1956 rows x 5 columns]

In [23]:
# checking for only comments on psy

df_with_keys.loc["Psy"]


COMMENT_ID  ... CLASS
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU  ...     1
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A  ...     1
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  ...     1
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04  ...     1
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw  ...     1
..                                           ...  ...   ...
345            z13th1q4yzihf1bll23qxzpjeujterydj  ...     0
346        z13fcn1wfpb5e51xe04chdxakpzgchyaxzo0k  ...     0
347          z130zd5b3titudkoe04ccbeohojxuzppvbg  ...     1
348          z12he50arvrkivl5u04cctawgxzkjfsjcc4  ...     1
349        z13vhvu54u3ewpp5h04ccb4zuoardrmjlyk0k  ...     0

[350 rows x 5 columns]

In [24]:
# save and write mearge data to a csv file

df_with_keys.to_csv("YoutubeSpamMergedData01.csv")

In [25]:
# getting data from mearge dataset.

df= pd.read_csv("YoutubeSpamMergedData01.csv")
df


Unnamed: 0  ...  CLASS
0           Psy  ...      1
1           Psy  ...      1
2           Psy  ...      1
3           Psy  ...      1
4           Psy  ...      1
...         ...  ...    ...
1951    Shakira  ...      0
1952    Shakira  ...      0
1953    Shakira  ...      0
1954    Shakira  ...      0
1955    Shakira  ...      0

[1956 rows x 7 columns]

In [26]:
#data size
df.size

13692

In [27]:
## Data cleaning

# checking for consistent column name

df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'COMMENT_ID', 'AUTHOR', 'DATE', 'CONTENT',
       'CLASS'],
      dtype='object')

In [28]:
# checking data types

df.dtypes

Unnamed: 0    object
Unnamed: 1     int64
COMMENT_ID    object
AUTHOR        object
DATE          object
CONTENT       object
CLASS          int64
dtype: object

In [30]:
# checking for missing nan

df.isnull().sum()

Unnamed: 0      0
Unnamed: 1      0
COMMENT_ID      0
AUTHOR          0
DATE          245
CONTENT         0
CLASS           0
dtype: int64

In [31]:
# check for date

df['DATE']

0              2013-11-07T06:20:48
1              2013-11-07T12:37:15
2              2013-11-08T17:34:21
3              2013-11-09T08:28:43
4              2013-11-10T16:05:38
                   ...            
1951    2013-07-13T13:27:39.441000
1952    2013-07-13T13:14:30.021000
1953    2013-07-13T12:09:31.188000
1954    2013-07-13T11:17:52.308000
1955    2013-07-12T22:33:27.916000
Name: DATE, Length: 1956, dtype: object

In [32]:
# getting author details 

df.AUTHOR

# if i convert the auther name to first and last bname then
#df[["FIRSTNAME"],["LASTNAME"]] = df['AUTHOR'].str.split(expand=True)

0                  Julius NM
1                adam riyati
2           Evgeny Murashkin
3            ElNino Melendez
4                     GsMega
                ...         
1951            Katie Mettam
1952    Sabina Pearson-Smith
1953           jeffrey jules
1954          Aishlin Maciel
1955             Latin Bosch
Name: AUTHOR, Length: 1956, dtype: object

In [33]:
## working with text content

df_data = df[['CONTENT','CLASS']]

# to see those values content =  comments && class = true/false

df_data

CONTENT  CLASS
0     Huh, anyway check out this you[tube] channel: ...      1
1     Hey guys check out my new channel and our firs...      1
2                just for test I have to say murdev.com      1
3      me shaking my sexy ass on my channel enjoy ^_^       1
4               watch?v=vtaRGgvGtWQ   Check this out .      1
...                                                 ...    ...
1951  I love this song because we sing it at Camp al...      0
1952  I love this song for two reasons: 1.it is abou...      0
1953                                                wow      0
1954                            Shakira u are so wiredo      0
1955                         Shakira is the best dancer      0

[1956 rows x 2 columns]

In [34]:
# to see new dataset coluimns
df_data.columns

Index(['CONTENT', 'CLASS'], dtype='object')

In [35]:
# inserting data inn x,y for visualization
df_x = df_data['CONTENT']
df_y = df_data['CLASS']

In [36]:
### Feature Extraction From Text

#1 CountVectorizer
#2 TfidfVectorizer

cv = CountVectorizer()

ex = cv.fit_transform(["Great song but check this out","What is this song"])

In [37]:
# convertion to arry

ex.toarray()

array([[1, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1]])

In [38]:
# gettingh feature name

cv.get_feature_names()

['but', 'check', 'great', 'is', 'out', 'song', 'this', 'what']

In [39]:
# extrat feature with CountVectorizer

corpus = df_x
cv = CountVectorizer()
X = cv.fit_transform(corpus)

In [40]:
# convertingf x to an aray

X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [41]:
# get the feature names

cv.get_feature_names()

['00',
 '000',
 '002',
 '018',
 '02',
 '034',
 '04',
 '047000',
 '05',
 '053012',
 '0687119038',
 '08',
 '09',
 '0cb8qfjaa',
 '0d878a889c',
 '0dbhjzdw0lbsjbi40gxm0d0p5krhv8xinqli53__wqbahs8zx4mjhw5vwrkpxfoeks',
 '0laviqu2b',
 '10',
 '100',
 '1000',
 '10000000',
 '1000000000',
 '100000415527985',
 '100005244783212',
 '100007085325116',
 '10001',
 '100877300245414',
 '101721377578919894134',
 '10200253113705769',
 '1030',
 '104999962146104962510',
 '10626048',
 '10626835',
 '106865403',
 '107297364',
 '1073741825',
 '1073741828',
 '1073741830',
 '1073741943',
 '108k',
 '109',
 '10b35481',
 '11',
 '1111',
 '1111111111111111111',
 '111719098841907',
 '111982027348137311818',
 '112720997191206369631',
 '11cpwb',
 '11th',
 '12',
 '123',
 '124',
 '124923004',
 '126',
 '127',
 '128gb',
 '12year',
 '13',
 '13017194',
 '131275322914',
 '131338190916',
 '1337',
 '1340488',
 '1340489',
 '1340490',
 '1340491',
 '1340492',
 '1340493',
 '1340494',
 '1340499',
 '1340500',
 '1340502',
 '1340503',
 '134

In [42]:
# module building

from sklearn.model_selection import train_test_split

In [43]:
#training
X_train,X_test,y_train,y_test = train_test_split(X,df_y,test_size=0.33,random_state = 42)

In [44]:
# see X_train
X_train

<1310x4454 sparse matrix of type '<class 'numpy.int64'>'
	with 17525 stored elements in Compressed Sparse Row format>

In [45]:
# Naive Bayes Classifire

from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)


0.9195046439628483

In [46]:
# acuracy of our model

print(f"Accuracy of model {clf.score(X_test,y_test)*100} %")

Accuracy of model 91.95046439628483 %


In [47]:
## predict with our model

clf.predict(X_test)

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,

In [48]:
# a simple prediction
comment = ["Check this out"]

vect = cv.transform(comment).toarray()

In [49]:
clf.predict(vect)

array([1])

In [50]:
class_dict = {"Not Spam":0,"Spam":1}
class_dict.values()

dict_values([0, 1])

In [51]:
if clf.predict(vect) == 1:
    print("Spam")
else:
    print("Not Spam")

Spam


In [ ]:
## Test 2

In [52]:
# simple Prerdiction 2
comment1 = [str(input())]
vect = cv.transform(comment1).toarray()
print(clf.predict(vect))
if clf.predict(vect) == 1:
    print("Spam")
else:
    print("Not Spam")

good song
[0]
Not Spam


In [53]:
## Save The model

import pickle as pk

In [54]:
naivebayesML = open("YtbSpam_model.pkl","wb")

In [56]:
pk.dump(clf,naivebayesML)

In [57]:
naivebayesML.close()

In [58]:
## load the model

ytb_model = open("YtbSpam_model.pkl","rb")

In [59]:
new_model = pk.load(ytb_model)

In [61]:
new_model

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)